### ISSUE TITLE
docs for how to upload a release asset

### ISSUE THREAD

**Issue by tmarshall** [caarbon/hub-o-matic#1]
see [the github docs](https://developer.github.com/v3/repos/releases/#upload-a-release-asset)

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.
> 
> _\- Jimi Hendrix_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.
> 
> _\- Jimi Hendrix_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.
> 
> _\- Ernest Hemingway_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> The dead cannot cry out for justice. It is a duty of the living to do so for them.
> 
> _\- Lois McMaster Bujold_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> Life is hard. Then you die. Then they throw dirt in your face. Then the worms eat you. Be grateful it happens in that order.
> 
> _\- David Gerrold_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> People living deeply have no fear of death.
> 
> _\- Anaïs Nin_

**Comment by caamuerte** [comment]
@tmarshall :heart: :skull:

> Sleep, those little slices of death — how I loathe them.
> 
> _\- Edgar Allan Poe_
